### PR TITLE
qtcurve lib32 ready for Plasma 5, git snapshot

### PR DESCRIPTION
**Pull request by FadeMind**
Reference: https://github.com/manjaro/packages-community/pull/77

Regards

### CODE REVIEW

**Comment by oberon2007** [comment]
How do we name and version these? Following VCS package guidelines we normally remove "-git" from pkgnames and prefix the latest release. In this case I'm in secure: The [arch package](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/lib32-qtcurve#n14) doesn't give away an online source where I could check for releases, but assuming **1.8.18** is the latest, should we use **1.8.18.rev.commit** ?

**Comment by FadeMind** [comment]
@oberon2007 
The Main version of qtcurve described in Settings it is:

**1.8.18-244-g330bfa5**
screenshot_20151207_135203
git versioning (used in PKGBUILD) give:
**r4139.330bfa5**
IMO version should be extracted from CMake some how and converted to:
**1.8.18.244.g330bfa5**
where **330bfa5** is lastest commit short hash OR just used here in hard way.

Reference: https://projects.archlinux.org/pacman.git/tree/proto/PKGBUILD-vcs.proto

**Comment by philmmanjaro** [comment]
You can use something similar like I use for **calamares-dev**:
```
pkgver() {
	cd ${srcdir}/calamares
	_ver="$(cat CMakeLists.txt | grep -m3 -e CALAMARES_VERSION_MAJOR -e CALAMARES_VERSION_MINOR -e CALAMARES_VERSION_PATCH | grep -o "[[:digit:]]*" | xargs)"
	_git=".r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
	_patchver="$(cat CMakeLists.txt | grep -m3 -e CALAMARES_VERSION_PATCH | grep -o "[[:digit:]]*" | xargs)"
	echo -e "${_ver// /.}${_git}"
	sed -i -e "s|CALAMARES_VERSION_PATCH $_patchver|CALAMARES_VERSION_PATCH $_patchver$_git|g" CMakeLists.txt
	rm -r ${srcdir}/calamares/.git
	rm -r ${srcdir}/calamares-manjaro/.git
}
```

As usual get the version from the CMakeList.txt file. Simply replace **CALAMARES_VERSION_MAJOR** with **QTCURVE_VERSION_MAJOR** and so on.

**Comment by FadeMind** [comment]
@philmmanjaro :

CMake code:

## Version
set(QTCURVE_VERSION_MAJOR "1")
set(QTCURVE_VERSION_MINOR "8")
set(QTCURVE_VERSION_PATCH "18")
set(QTCURVE_VERSION "${QTCURVE_VERSION_MAJOR}.${QTCURVE_VERSION_MINOR}")
set(QTCURVE_VERSION_FULL "${QTCURVE_VERSION}.${QTCURVE_VERSION_PATCH}")

find_package(Git QUIET)
add_custom_command(OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/version.cpp"
  DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/tools/gen-version.sh"
  WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}")
add_custom_target(gen-git-ver ALL
  COMMAND "${CMAKE_CURRENT_SOURCE_DIR}/tools/gen-version.sh"
  "${CMAKE_CURRENT_BINARY_DIR}/version.cpp" "${QTCURVE_VERSION_FULL}"
  "${GIT_EXECUTABLE}"
  DEPENDS "${CMAKE_CURRENT_BINARY_DIR}/version.cpp")

**Comment by oberon2007** [comment]
It also works quite simply with
```
pkgver() {
  cd "$_pkgbase"
  git describe --long | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}
```
My question was mostly if we should remove the -git in pkgnames... ;)

**Comment by FadeMind** [comment]
@oberon2007  You will commit this changes? (in names (cuting -git) and versioning? I don't want double merging :sweat_smile:

**Comment by oberon2007** [comment]
yes. if that's ok. will do :)

**Comment by FadeMind** [comment]
IT is OK. and give proper versioning ;)

**Comment by oberon2007** [comment]
[done](https://github.com/manjaro/packages-multilib/commit/e1880a3d3bd0ac6b46e4898a50a49b3920265cb3) only problem: I seem to not know how to build a multilib pkg with buildpkg 8^} Do I have to change makepkg config somewhere? Please advise!
```
==> Installing missing dependencies...
error: target not found: gcc-multilib
error: target not found: lib32-gtk2
error: target not found: lib32-qt4
```
;)

**Comment by FadeMind** [comment]
You need to install them.
BUT first of all please merge qtcurve. 

https://github.com/manjaro/packages-community/pull/77

You make typos. I figure out then. 
https://www.archlinux.org/packages/multilib/x86_64/lib32-gtk2/
https://www.archlinux.org/packages/multilib/x86_64/lib32-qt4/

**Comment by FadeMind** [comment]
@oberon2007 
I will fix whole issue.

**Comment by oberon2007** [comment]
Got it @FadeMind . I have everything ready here. Will push everything at once a little later.

**Comment by philmmanjaro** [comment]
`buildpkg -p <package> -a multilib`

**Comment by oberon2007** [comment]
Aah, sure. Thank you @philmmanjaro :)

**Pull request merged**
